swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Devsurfing-messages

# Describe your paths here
paths:

  /:sent_id/to/:received_id/:sent_name/received_name:
    post:
      description: |
        Cria e insere mensagens em uma conversa recebendo por pela url os dados dos usuários e pelo corpo da requisição a mensagem
      responses:
        200:
          description: Resposta de sucesso, devolve um JSon

  /:sent_id/to/:received_id:
    get:
      description: |
        Obtem determinada conversa através dos ids dos usuários
      responses:
        200:
          description: retorna um json com as mensagens da conversa

  /all/:user_id:
    get:
      description: |
        através do ID do usuário obtem o nome e ID de todos os usuários com os quais o usuário específico possui conversas
      responses:
        200:
          description: retorna um JSON contendo o nome e o ID dos usuários
