swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Devsurfing-messages

# Describe your paths here
paths:
  
  /:message_id:
    get:
      description: |
        Obtem determinada conversa
      parameters:
        -
          name: message_id
          in: query
          description: o id da conversa
          required: true
          type: string
      responses:
        200:
          description: Resposta de sucesso, devolve um JSon
           
  /save:
    post:
      description: |
        Recebe um objeto que com todos os dados para criar a conversa
      responses:
        200:
          description: OK
  
  /save/:message_id:
    put:
      description: |
        Recebe um objeto que com todos os dados para inserir uma nova mensagem na conversa
      responses:
        200:
          description: OK
          
  /getall/:user_id:
    get:
      description: |
        obtem todas as conversas de determinado usuário
      responses:
        200:
          description: OK
      